### ISSUE TITLE
Opposite parallax?

### ISSUE THREAD

**Issue by emmadalby** [hwthorn/parallaxify#16]
Hi!

This is a great plugin and I have it all working which is good but at the moment the image I have the parallax on is moving **TOWARDS** the mouse at the moment and I want it to move **AWAY** from the mouse move (like in the opposite direction) if you get me?

Is this possible? And if so, how do I go about doing it as I am at a total loss...

Any help would be greatly appreciated.

Thank you.

**Comment by hwthorn** [comment]
just use negative values and it will move in opposite of mouse.

**Comment by emmadalby** [comment]
Ahhh.. thank you so much!! I have been looking at this for way too long and must of missed that.

 

Thanks so much for the quick reply too man I really appreciate it.

 

Kind Regards,

 

Emma Dalby

 

digital by default.

 <http://www.wearedigitalbydefault.co.uk/> www.wearedigitalbydefault.co.uk

01283 791007

**Comment by yeomann** [comment]
Replied you on email already emma, not exactly it goes with opposite direction. but i think try this to get some idea http://jsfiddle.net/X7UwG/854/ and maybe you can achieve with this plugin as well.

**Comment by emmadalby** [comment]
Thanks for the help guys. It's sorted now and looks great! :)

**Comment by miroamarillo** [comment]
Thanks to a previos ticket, here's the code:
```javascript
  // defining your own positioning function
  $.parallaxify.positionProperty.inverted = {
      setPosition: function($element, left, originalLeft, top, originalTop) {
        $element.css('transform', 'translate(' + (originalLeft - left) + 'px, ' + (originalTop - top) + 'px)');
      }
  };
  // using your own positioning function
  $('#parallax').parallaxify({
      positionProperty: 'inverted',
      responsive: true,
      motionType: "natural",
      mouseMotionType: "gaussian",
      motionAngleX: 90,
      motionAngleY: 90,
      alphaFilter: 0.5,
      adjustBasePosition: true,
      alphaPosition: 0.025
  });
```

**Comment by emmadalby** [comment]
Hi @miroamarillo 

Sorry, only just seen this. I just used negative values instead of positive ones as suggested above by @hwthorn 

Worked great.

**Comment by miroamarillo** [comment]
@emmadalby Thanks!

**Comment by emmadalby** [comment]
No problem 😊
