### ISSUE TITLE
$.parallaxify on element not working

### ISSUE THREAD

**Issue by R4c00n** [hwthorn/parallaxify#6]
Hi,
when I try to add a parallax to a single element instead of running it global, nothing happens.
[JSFiddle](http://jsfiddle.net/Lb0uqe6c/1/)

Is this a known problem or am I doing something wrong?

**Comment by nevace** [comment]
I'm having the same issue.

**Comment by franckdelage** [comment]
+1

**Comment by franckdelage** [comment]
Ok, found the problem, which is not a problem, but should be more precised in the README.

When you apply parallax() on one element, it's not **this** element that is parallaxified, but the elements wrapped into it !

```html
<div id="wrapper">
  <div id="element1"></div>
  <div id="element2"></div>
</div>
```

then :

```javascript
$('#wrapper').parallaxify()
```

will parralaxify #element1 and #element2.
