### ISSUE TITLE
Background image parallax out of its container

### ISSUE THREAD

**Issue by jeffceriello** [hwthorn/parallaxify#9]
Hi,

I'm trying to parallax horizontally a background image using this inline attribute

`data-parallaxify-background-range-x="-40"`

and this is my js call

```
$('#hero').parallaxify({
        horizontalParallax: true,
        verticalParallax: false,
        parallaxBackgrounds: true,
        parallaxElements: false,
        // options include 'position' or 'transform' using css transformations
        positionProperty: 'position',
        // (upon orientation changes or window resizing element positions are reevaluated
        responsive: true,
        // enable or disable mouse or gyroscope data as input for the plugin
        useMouseMove: true,
        useGyroscope: true,
        // use a Low Pass Filter to smooth sensor readings (1 = no filter)
        alphaFilter: 0.9,
        // set which motion type algorithm is to be used
        // options include 'natural', 'linear', 'gaussian', or 'performance'
        motionType: 'natural',
        mouseMotionType: 'gaussian',
        // define which sensor input has priority over the other
        // options are either 'mouse' or 'gyroscope'
        inputPriority: 'mouse',
        // define the delta angle (0 < motionAngle < 90) 
        // that is used to render max parallax in this direction
        motionAngleX: 80,
        motionAngleY: 80,
        // enable of adjustment of base position (using a Low Pass Filter)
        // (adapting to device usage while plugin is running)
        adjustBasePosition: true,
        // alpha for Low Pass Filter used to adjust average position
        alphaPosition: 0.05
    });
```

The background image has a `background-size of 120% auto;`

When I move the mouse around, the background image starts from a background-position of 35px and it looks really bad. I would like not to parallax out of its container so that I don't see the background color behind the element.

Ideally the background image should move a certain amount starting from 50% horizontally. It should start with:

`background-position: 50% 50%;`

And then when moving the mouse for example to the right it would go:

`background-position: 40% 50%;`

And when moving to the left:

`background-position: 60% 50%;`

Without exceeding its container boundaries.

Is that possible?

An example of the issue would be on this page http://dev.thinktravellive.com/en/thoughts/

Thanks
Jeff

**Comment by jeffceriello** [comment]
Hi there,

Any update on this? I just want to know at least if I will be able to use this plugin or should I remove it altogether.

Thanks
Jeff

**Comment by hwthorn** [comment]
Jeff,

pelase read the instructions closely. Unfortunately you did not provide
enough information to easily trouble shoot your issue - it is always
recommend to provide a jsfiddle, etc. My guess is that your starting CSS
background position is 0,0 which in conclusion will move your background
out of bounds. to ensure the right positioning you will have to both ensure
your image is large enough to cover the area and is postponed centered
before you apply the parallax. As for if you should or should not use the
plugin - I cannot answer that question for you. If you will not be using it
you might want to remove it to increase page load speeds.

**Comment by jeffceriello** [comment]
Hi @hwthorn, thank you for your reply.

Here is a simplified jsfiddle https://jsfiddle.net/6rsrveyL/12/

As you can see I have set the background position: center center in the CSS before I apply the parallax but the image moves to 0,0 and parallaxes out of bounds.

Is it possible to have the background image centered and parallax starting from the center rather than 0,0?

Am I doing something wrong?

Thank you
Jeff

**Comment by hwthorn** [comment]
just define a max parallax and set initial CSS position to minimum that
distance as negative values. i.e. for a 100px parallax in x-axis set to
-100px for x-axis easiest way to ensure image covers set to
background-size:120% or whatever suits for your example.
